/**
 * React Query hooks.
 *
 * Query keys are the caching contract. Catalogue data is effectively immutable
 * between pipeline runs, so it gets a long stale time and is never refetched on
 * focus — that alone removes most of the redundant network traffic the old client
 * generated by refetching on every mount.
 *
 * Personal data (ratings, watchlist) is mutated optimistically: the star fills and
 * the bookmark toggles immediately, and the mutation reconciles afterwards. Waiting
 * on a round trip before updating the UI is what made the old app feel sluggish.
 */

import {
  useInfiniteQuery,
  useMutation,
  useQuery,
  useQueryClient,
} from '@tanstack/react-query';
import { movies, ratings, recommendations, system, watchlist } from './api';
import { useAuth } from './auth';

/** Catalogue rows change only when a pipeline runs. */
const CATALOGUE = { staleTime: 10 * 60 * 1000, gcTime: 30 * 60 * 1000 };
/** Personal data should be fresh but not chatty. */
const PERSONAL = { staleTime: 60 * 1000 };

export const keys = {
  home: ['home'],
  genres: ['genres'],
  browse: (params) => ['browse', params],
  search: (params) => ['search', params],
  movie: (id) => ['movie', id],
  similar: (id) => ['similar', id],
  recommendations: (params) => ['recommendations', params],
  myRatings: ['my-ratings'],
  ratingHistory: ['rating-history'],
  ratingStats: ['rating-stats'],
  watchlist: ['watchlist'],
  watchlistIds: ['watchlist-ids'],
  stats: ['system-stats'],
  metrics: ['system-metrics'],
};

/* ------------------------------------------------------------------ catalogue */

export function useHomeFeed() {
  return useQuery({
    queryKey: keys.home,
    queryFn: ({ signal }) => movies.home(signal),
    ...CATALOGUE,
  });
}

export function useGenres() {
  return useQuery({
    queryKey: keys.genres,
    queryFn: ({ signal }) => movies.genres(signal),
    staleTime: 60 * 60 * 1000,
  });
}

export function useMovie(id) {
  return useQuery({
    queryKey: keys.movie(id),
    queryFn: ({ signal }) => movies.detail(id, signal),
    enabled: Boolean(id),
    ...CATALOGUE,
  });
}

export function useSimilar(id, limit = 14) {
  return useQuery({
    queryKey: keys.similar(id),
    queryFn: ({ signal }) => movies.similar(id, limit, signal),
    enabled: Boolean(id),
    ...CATALOGUE,
    // The engine may not be loaded; an empty row is better than an error state.
    retry: false,
  });
}

/** Paginated browse with page-to-page continuity so the grid does not flash. */
export function useBrowse(params) {
  return useInfiniteQuery({
    queryKey: keys.browse(params),
    queryFn: ({ pageParam = 1, signal }) =>
      movies.browse({ ...params, page: pageParam }, signal),
    getNextPageParam: (last) =>
      last?.pagination?.has_next ? last.pagination.page + 1 : undefined,
    initialPageParam: 1,
    ...CATALOGUE,
  });
}

/** Paginated search for the dedicated results page. */
export function useSearchResults(term) {
  const query = term?.trim() ?? '';
  return useInfiniteQuery({
    queryKey: ['search-results', query],
    queryFn: ({ pageParam = 1, signal }) =>
      movies.search({ q: query, page: pageParam, page_size: 36 }, signal),
    getNextPageParam: (last) =>
      last?.pagination?.has_next ? last.pagination.page + 1 : undefined,
    initialPageParam: 1,
    enabled: query.length >= 2,
    staleTime: 2 * 60 * 1000,
  });
}

export function useSearch(term, { enabled = true } = {}) {
  const query = term?.trim() ?? '';
  return useQuery({
    queryKey: keys.search({ q: query }),
    queryFn: ({ signal }) => movies.search({ q: query, page_size: 12 }, signal),
    // Single characters match too much to be useful and cost a request per keystroke.
    enabled: enabled && query.length >= 2,
    staleTime: 2 * 60 * 1000,
    placeholderData: (previous) => previous,
  });
}

/* -------------------------------------------------------------- personal data */

export function useMyRatings() {
  const { isAuthenticated } = useAuth();
  return useQuery({
    queryKey: keys.myRatings,
    queryFn: ({ signal }) => ratings.mine(signal),
    enabled: isAuthenticated,
    select: (data) => data?.ratings ?? {},
    ...PERSONAL,
  });
}

export function useWatchlistIds() {
  const { isAuthenticated } = useAuth();
  return useQuery({
    queryKey: keys.watchlistIds,
    queryFn: ({ signal }) => watchlist.ids(signal),
    enabled: isAuthenticated,
    select: (data) => new Set((data?.movie_ids ?? []).map(Number)),
    ...PERSONAL,
  });
}

export function useRatingHistory(pageSize = 24) {
  const { isAuthenticated } = useAuth();
  return useInfiniteQuery({
    queryKey: keys.ratingHistory,
    queryFn: ({ pageParam = 1, signal }) =>
      ratings.history({ page: pageParam, page_size: pageSize }, signal),
    getNextPageParam: (last) =>
      last?.pagination?.has_next ? last.pagination.page + 1 : undefined,
    initialPageParam: 1,
    enabled: isAuthenticated,
  });
}

export function useWatchlist(pageSize = 24) {
  const { isAuthenticated } = useAuth();
  return useInfiniteQuery({
    queryKey: keys.watchlist,
    queryFn: ({ pageParam = 1, signal }) =>
      watchlist.list({ page: pageParam, page_size: pageSize }, signal),
    getNextPageParam: (last) =>
      last?.pagination?.has_next ? last.pagination.page + 1 : undefined,
    initialPageParam: 1,
    enabled: isAuthenticated,
  });
}

export function useTasteStats() {
  const { isAuthenticated } = useAuth();
  return useQuery({
    queryKey: keys.ratingStats,
    queryFn: ({ signal }) => ratings.stats(signal),
    enabled: isAuthenticated,
    ...PERSONAL,
  });
}

export function useRecommendations(params = {}) {
  const { isAuthenticated } = useAuth();
  return useQuery({
    queryKey: keys.recommendations(params),
    queryFn: ({ signal }) => recommendations.get(params, signal),
    enabled: isAuthenticated,
    staleTime: 2 * 60 * 1000,
    retry: false,
    placeholderData: (previous) => previous,
  });
}

/* ------------------------------------------------------------------ mutations */

/**
 * Invalidates everything derived from the user's taste.
 * Recommendations, stats and history all shift when a rating changes.
 */
function invalidateTaste(queryClient) {
  queryClient.invalidateQueries({ queryKey: ['recommendations'] });
  queryClient.invalidateQueries({ queryKey: keys.ratingStats });
  queryClient.invalidateQueries({ queryKey: keys.ratingHistory });
}

export function useRateMovie() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: ({ movieId, rating }) => ratings.submit(movieId, rating),
    onMutate: async ({ movieId, rating }) => {
      await queryClient.cancelQueries({ queryKey: keys.myRatings });
      const previous = queryClient.getQueryData(keys.myRatings);
      queryClient.setQueryData(keys.myRatings, (current) => ({
        ratings: { ...(current?.ratings ?? {}), [String(movieId)]: rating },
      }));
      return { previous };
    },
    onError: (_error, _variables, context) => {
      // Put the old value back so the UI does not claim a rating that failed.
      if (context?.previous) queryClient.setQueryData(keys.myRatings, context.previous);
    },
    onSuccess: () => invalidateTaste(queryClient),
  });
}

export function useRemoveRating() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: (movieId) => ratings.remove(movieId),
    onMutate: async (movieId) => {
      await queryClient.cancelQueries({ queryKey: keys.myRatings });
      const previous = queryClient.getQueryData(keys.myRatings);
      queryClient.setQueryData(keys.myRatings, (current) => {
        const next = { ...(current?.ratings ?? {}) };
        delete next[String(movieId)];
        return { ratings: next };
      });
      return { previous };
    },
    onError: (_error, _variables, context) => {
      if (context?.previous) queryClient.setQueryData(keys.myRatings, context.previous);
    },
    onSuccess: () => invalidateTaste(queryClient),
  });
}

export function useRateBatch() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (items) => ratings.submitBatch(items),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: keys.myRatings });
      invalidateTaste(queryClient);
    },
  });
}

export function useToggleWatchlist() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: ({ movieId, saved }) =>
      saved ? watchlist.remove(movieId) : watchlist.add(movieId),
    onMutate: async ({ movieId, saved }) => {
      await queryClient.cancelQueries({ queryKey: keys.watchlistIds });
      const previous = queryClient.getQueryData(keys.watchlistIds);
      queryClient.setQueryData(keys.watchlistIds, (current) => {
        const ids = new Set((current?.movie_ids ?? []).map(Number));
        if (saved) ids.delete(Number(movieId));
        else ids.add(Number(movieId));
        return { movie_ids: [...ids] };
      });
      return { previous };
    },
    onError: (_error, _variables, context) => {
      if (context?.previous) queryClient.setQueryData(keys.watchlistIds, context.previous);
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: keys.watchlist });
    },
  });
}

/* --------------------------------------------------------------------- system */

export function useCatalogueStats() {
  return useQuery({
    queryKey: keys.stats,
    queryFn: ({ signal }) => system.stats(signal),
    staleTime: 5 * 60 * 1000,
    retry: false,
  });
}

export function useModelMetrics() {
  return useQuery({
    queryKey: keys.metrics,
    queryFn: ({ signal }) => system.metrics(signal),
    staleTime: 60 * 60 * 1000,
    retry: false,
  });
}
